data : 
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file : data.zip
  unzip_data_loc : data
  bad_data_dir : bad_data
  parent_data_dir : PetImages

params :
  image_shape : [180,180,3]
  optimizer_lr : 0.001
  loss_fn : sparse_categorical_crossentropy
  metrics : ["accuracy"]

model :
  model_dir: Artifacts